CREATE TABLE administratori (
    id INT AUTO_INCREMENT PRIMARY KEY,
    admin_ime VARCHAR(100) NOT NULL,
    admin_lozinka VARCHAR(255) NOT NULL
);

CREATE TABLE regkorisnici (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ime VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    lozinka VARCHAR(255) NOT NULL
);

CREATE TABLE poruke (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ime VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    poruka TEXT NOT NULL,
    datum TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);